apiVersion: v1
kind: Namespace
metadata:
   name: testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casbpm
  namespace: testing
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: cascontainer
        image: sandeepfile/tomcat-cas:latest
        ports:
        - containerPort: 8280
        resources:
          requests:
           memory: 2Gi
           cpu: 1
          limits:
            memory: 5Gi
            cpu: 2
        livenessProbe:
          tcpSocket:
            port: 8280
          initialDelaySeconds: 200
          periodSeconds: 100
          timeoutSeconds: 360
        readinessProbe:
          httpGet:
            path: activiti-app/
            port: 8280
          initialDelaySeconds: 200
          periodSeconds: 100
          timeoutSeconds: 360
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
  namespace: testing
spec:
  type: NodePort
  selector:
    app: testing
  ports:
  - port: 8280
    nodePort: 32720